#!/usr/bin/env bun
/**
 * Generate the example programs into a module the site can import.
 *
 * The examples are read from `../examples/*.fxc` — the same files the Rust test
 * suite runs — rather than copied into the page. A copy would be free to drift;
 * this cannot, and `bun run build:examples` re-reads them every time.
 *
 * This needs no Rust toolchain: it only reads text files and writes one module.
 *
 * Where they go is a deliberate choice: the examples belong to **documentation**,
 * not to the editor. The editor's workspace holds the user's own program and
 * nothing else, so opening the workbench never lands you in a folder full of
 * files you did not write.
 */
import { mkdir } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const web = dirname(here);
const root = dirname(web);
const destination = join(web, 'src', 'lib', 'examples.generated.ts');

/** The first `//` line of a program, as a one-line description. */
function summary(source: string): string {
	for (const line of source.split('\n')) {
		const trimmed = line.trim();
		if (trimmed.startsWith('//')) {
			const body = trimmed.replace(/^\/+/, '').trim();
			// Skip banner rules and section headings — the first one of those is
			// never a useful description.
			if (body && !/^[-=]+$/.test(body) && !body.endsWith(':')) return body;
		} else if (trimmed) {
			break;
		}
	}
	return '';
}

async function collect(pattern: string): Promise<string[]> {
	const paths: string[] = [];
	for await (const path of new Bun.Glob(pattern).scan({ cwd: root })) paths.push(path);
	return paths.sort();
}

const libraries: Record<string, string> = {};
for (const path of await collect('examples/lib/*.fxc')) {
	// Keyed by their bare name because a program's `#include "lib/…"` resolves
	// relative to the entry document, which is what these paths are written for.
	libraries[path.replace(/^examples\//, '')] = await Bun.file(join(root, path)).text();
}

const examples: { name: string; summary: string; source: string }[] = [];
for (const path of await collect('examples/*.fxc')) {
	const source = await Bun.file(join(root, path)).text();
	examples.push({
		name: path.replace(/^examples\//, '').replace(/\.fxc$/, ''),
		summary: summary(source),
		// The embedded `#tests` table comes along inside `source` untouched.
		source
	});
}

const header = `// Generated by web/scripts/bundle-examples.ts from examples/*.fxc.
// Do not edit — run \`bun run build:examples\` instead.
//
// Read by the documentation pages, not by the editor. The editor's workspace is
// the user's own file and nothing else.
`;

const body = `
/** One example program, as written in \`examples/\`. */
export interface Example {
	/** The file name without \`.fxc\`, e.g. \`determinant\`. */
	name: string;
	/** The program's first comment line, or an empty string. */
	summary: string;
	/** The whole program, including any \`#tests\` table. */
	source: string;
}

/** The libraries under \`examples/lib/\`, keyed by the path an \`#include\` uses. */
export const libraries: Record<string, string> = ${JSON.stringify(libraries, null, '\t')};

/** Every example, in file order. */
export const examples: Example[] = ${JSON.stringify(examples, null, '\t')};
`;

await mkdir(dirname(destination), { recursive: true });
await Bun.write(destination, header + body);

console.log(
	`${relative(root, destination)}: ${examples.length} example(s), ` +
		`${Object.keys(libraries).length} library file(s)`
);
