#!/bin/sh
# Build everything the web page needs.
#
#   ./web/build.sh          build the wasm module and bundle the examples
#   python3 -m http.server  # (from the repository root) then open /web/
#
# Two generated artifacts:
#
#   web/fx_wasm.wasm   the module, from crates/fx-wasm
#   web/examples.js    the example programs, read from examples/*.fxc
#
# The examples are *generated from the repository's own example files* rather
# than copied into the page, so the site can never show a stale or hand-edited
# version of a program the test suite checks.
#
# Only the Rust target is needed — there is no `wasm-bindgen`, no `wasm-pack` and
# no `wasm-opt`, because the module's ABI is three plain `extern "C"` functions
# over a JSON string (see `crates/fx-wasm/src/abi.rs`). The only prerequisite is:
#
#     rustup target add wasm32-unknown-unknown
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(dirname -- "$here")

cd "$root"
cargo build --profile wasm --target wasm32-unknown-unknown -p fx-wasm

built=target/wasm32-unknown-unknown/wasm/fx_wasm.wasm
cp "$built" "$here/fx_wasm.wasm"

# Bundle the examples. `lib/` is keyed by its bare name because an example that
# `#include`s a library resolves it relative to the entry document, which is
# always `main.fxc` in the page.
python3 - "$root" "$here/examples.js" <<'PYTHON'
import json
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
out = pathlib.Path(sys.argv[2])

libraries = {
    f"lib/{path.name}": path.read_text(encoding="utf-8")
    for path in sorted((root / "examples" / "lib").glob("*.fxc"))
}


def summary(text):
    """The first `//` line of a program, as a one-line description."""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("//"):
            body = stripped.lstrip("/").strip()
            if body and not body.startswith("-") and not body.endswith(":"):
                return body
        elif stripped:
            break
    return ""


examples = [
    {
        "name": path.stem,
        "summary": summary(path.read_text(encoding="utf-8")),
        "source": path.read_text(encoding="utf-8"),
    }
    for path in sorted((root / "examples").glob("*.fxc"))
]

# `#tests` blocks are what the site's "Run tests" button uses, so they come along
# inside `source` untouched.
out.write_text(
    "// Generated by web/build.sh from examples/*.fxc -- do not edit by hand.\n"
    "// Regenerate with `./web/build.sh`.\n\n"
    f"export const libraries = {json.dumps(libraries, ensure_ascii=False, indent=2)};\n\n"
    f"export const examples = {json.dumps(examples, ensure_ascii=False, indent=2)};\n",
    encoding="utf-8",
)
print(f"web/examples.js: {len(examples)} example(s), {len(libraries)} library file(s)")
PYTHON

raw=$(wc -c < "$here/fx_wasm.wasm")
gzipped=$(gzip -9 -c "$here/fx_wasm.wasm" | wc -c)
printf 'web/fx_wasm.wasm: %s bytes (%s bytes gzipped)\n' "$raw" "$gzipped"
